[package]
name = "NazgandLean3"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "ba80091d8268f1aa9c3e4d5c5b6d1df0dff68b19"}
